# Generated by Django 4.1.7 on 2023-02-20 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homecommon', '0003_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_num', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('product_stock', models.BigIntegerField()),
                ('Product_price', models.FloatField()),
                ('image', models.ImageField(upload_to='product/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homecommon.seller')),
            ],
        ),
    ]
